### PR TITLE
Propagate track_kind down through calls instead of using parent.

### PR DESCRIPTION
**Pull request by ssteinbach**
I took a second look at your PR.  I didn't notice before that you're using `_set_parent()`, which is likely to go away as we move to C++.  To anticipate this change, Here is another way to do this - we pass the track kind down through the function calls as it goes.  What do you think?

### CODE REVIEW

**Comment by apetrynet** [comment]
Hi!
Yeah, I thought the `_set_parent()` might have to change in the future. Better to deal with it now I guess :) I'm sure this solution will work nicely as well, but I have to make sure I support the Stack vs Track case Robyn mentioned in nested timelines. In my latest push I added a function looking for a Track to make sure there is a kind attribute in the item.
I'll look at this with fresh eyes in the morning again.

**Comment by ssteinbach** [comment]
Cool.  If you have a unit test to add for that case, that would be great.  I *think* this will work, since `_write_stack` will pass `track_kind` down into `write_otio` without altering it.

**Comment by apetrynet** [comment]
Sure. I'll work on it tomorrow. Thanks!

**Comment by apetrynet** [comment]
I'll just close this since I did the same changes in my repo.

**Pull request closed without merging**
